name: Deploy to EC2
 
on:
  push:
    branches:
      - main # Adjust to your branch name
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 15.207.248.68
        username: ubuntu
        key: ${{ secrets.DEMO_AMI_KEYPAIR_AWS }}
        port: 22
        script: |
          cd /var/www/html/github-servers
          git pull origin main
          # Add other commands if needed, e.g., restarting services
          sudo systemctl restart apache2
